/**
 * lib/services/future-services.ts
 * Service layer interfaces for future features
 * Architecture preparation - not implemented yet
 *
 * Phase 6C-2 audit: duplicate plan/limits/ads interfaces removed.
 * Canonical types are now in lib/types/subscription.ts.
 * PremiumPlan → PlanDefinition, UsageLimits → UsageLimits, AdConfig → see below.
 */

import type { ConversionJob, ConversionResult, ConversionProgress } from '../types/conversion';
import type { FormatDefinition, FormatCategory } from '../types/formats';
// Canonical subscription types — do not duplicate these here
import type { PlanDefinition, UsageLimits as SubscriptionUsageLimits } from '../types/subscription';

// ---------------------------------------------------------------------------
// LONG-TAIL ENGINE (SEO PAGES)
// ---------------------------------------------------------------------------

export interface LongTailPageDefinition {
  slug: string;
  title: string;
  description: string;
  h1: string;
  keywords: string[];
  category: FormatCategory;
  inputFormat?: string;
  outputFormat?: string;
  searchVolume?: number;
  difficulty?: 'low' | 'medium' | 'high';
  relatedPages?: string[];
  autogenerated?: boolean;
}

export interface ILongTailEngine {
  generatePages(limit?: number): Promise<LongTailPageDefinition[]>;
  getPage(slug: string): Promise<LongTailPageDefinition | null>;
  getPagesByCategory(category: FormatCategory): Promise<LongTailPageDefinition[]>;
  getSitemapPages(): Promise<string[]>;
  regenerate(): Promise<void>;
}

// ---------------------------------------------------------------------------
// SEO ENGINE
// ---------------------------------------------------------------------------

export interface SeoMetadata {
  title: string;
  description: string;
  keywords: string[];
  canonical: string;
  ogImage?: string;
  schema?: Record<string, unknown>;
  hreflangs?: Record<string, string>;
}

export interface ISeoEngine {
  generateMetadata(page: string, locale: string): Promise<SeoMetadata>;
  generateSchema(type: string, data: Record<string, unknown>): Record<string, unknown>;
  optimizeTitle(title: string, keywords: string[]): string;
  optimizeDescription(description: string, keywords: string[]): string;
  generateHreflangs(path: string, locales: string[]): Record<string, string>;
}

// ---------------------------------------------------------------------------
// PREMIUM ENGINE
// Phase 6C-2 audit: PremiumPlan duplicates PlanDefinition from
// lib/types/subscription.ts. Marked deprecated; IPremiumEngine updated.
// ---------------------------------------------------------------------------

/**
 * @deprecated Use PlanDefinition from lib/types/subscription.ts.
 * Retained for backward compatibility — remove in Phase 6D cleanup.
 */
export interface PremiumPlan {
  id: string;
  name: string;
  price: number;
  currency: string;
  interval: 'month' | 'year';
  features: string[];
  limits: {
    dailyConversions: number;
    monthlyConversions: number;
    maxFileSize: number;
    maxFiles: number;
    batchEnabled: boolean;
    premiumFormats: boolean;
    priorityProcessing: boolean;
    noAds: boolean;
  };
}

export interface PremiumSubscription {
  id: string;
  userId: string;
  planId: string;
  status: 'active' | 'cancelled' | 'expired' | 'trial';
  currentPeriodStart: Date;
  currentPeriodEnd: Date;
  cancelAtPeriodEnd: boolean;
}

export interface IPremiumEngine {
  getPlans(): Promise<PremiumPlan[]>;
  getSubscription(userId: string): Promise<PremiumSubscription | null>;
  createSubscription(userId: string, planId: string): Promise<PremiumSubscription>;
  cancelSubscription(subscriptionId: string): Promise<void>;
  checkFeature(userId: string, feature: string): Promise<boolean>;
  getUsage(userId: string): Promise<Record<string, number>>;
}

// ---------------------------------------------------------------------------
// DOWNLOAD ENGINE
// ---------------------------------------------------------------------------

export interface DownloadRecord {
  id: string;
  jobId: string;
  userId?: string;
  filename: string;
  fileSize: number;
  mimeType: string;
  downloadUrl: string;
  expiresAt: Date;
  downloadCount: number;
  maxDownloads: number;
}

export interface IDownloadEngine {
  createDownload(job: ConversionJob, result: ConversionResult): Promise<DownloadRecord>;
  getDownload(id: string): Promise<DownloadRecord | null>;
  recordDownload(id: string): Promise<void>;
  cleanupExpired(): Promise<void>;
  generateDownloadUrl(record: DownloadRecord): string;
}

// ---------------------------------------------------------------------------
// LIMITS ENGINE
// Phase 6C-2 audit: UsageLimits interface removed — canonical type is
// SubscriptionUsageLimits from lib/types/subscription.ts.
// ---------------------------------------------------------------------------

export interface UsageRecord {
  date: Date;
  conversions: number;
  bytesProcessed: number;
  filesProcessed: number;
}

export interface ILimitsEngine {
  /** @see SubscriptionUsageLimits from lib/types/subscription.ts */
  getLimits(userId: string): Promise<SubscriptionUsageLimits>;
  getUsage(userId: string): Promise<UsageRecord>;
  canConvert(userId: string, size: number): Promise<boolean>;
  recordUsage(userId: string, bytes: number, files: number): Promise<void>;
  resetDailyLimits(): Promise<void>;
  resetMonthlyLimits(): Promise<void>;
}

// ---------------------------------------------------------------------------
// ADS ENGINE
// Phase 6C-2 audit: shouldShowAd now routes through SubscriptionService.
// AdConfig.enabled is redundant — use subscriptionService.shouldShowAds(planId).
// ---------------------------------------------------------------------------

export interface AdSlotConfig {
  id: string;
  name: string;
  location: 'header' | 'sidebar' | 'footer' | 'inline' | 'popup';
  size: 'leaderboard' | 'rectangle' | 'sidebar' | 'native';
  /** @deprecated Controlled via subscription plan feature 'adsEnabled' only */
  enabled: boolean;
  provider: 'adsense' | 'custom';
  slotId?: string;
}

/**
 * @deprecated Phase 6C-2: use subscriptionService.shouldShowAds(planId).
 * No component may check AdConfig.enabled directly.
 */
export interface AdConfig {
  provider: 'adsense' | 'custom' | 'none';
  publisherId?: string;
  slots: AdSlotConfig[];
  frequencyCap?: number;
  userTargeting?: boolean;
}

export interface IAdsEngine {
  getConfig(): Promise<AdConfig>;
  getSlot(location: string): Promise<AdSlotConfig | null>;
  /**
   * Phase 6C-2: always use subscriptionService.shouldShowAds(planId) instead.
   * The userId lookup resolves to planId → adsEnabled feature flag.
   */
  shouldShowAd(userId: string): Promise<boolean>;
  recordImpression(slotId: string): Promise<void>;
  recordClick(slotId: string): Promise<void>;
}

// ---------------------------------------------------------------------------
// AUTHENTICATION ENGINE
// ---------------------------------------------------------------------------

export interface AuthUser {
  id: string;
  email: string;
  name?: string;
  avatar?: string;
  tier: 'free' | 'premium' | 'enterprise';
  createdAt: Date;
  lastLoginAt?: Date;
}

export interface AuthSession {
  id: string;
  userId: string;
  token: string;
  expiresAt: Date;
  createdAt: Date;
}

export interface IAuthEngine {
  signUp(email: string, password: string): Promise<AuthUser>;
  signIn(email: string, password: string): Promise<AuthSession>;
  signOut(sessionId: string): Promise<void>;
  getSession(sessionId: string): Promise<AuthSession | null>;
  getUser(userId: string): Promise<AuthUser | null>;
  getCurrentUser(): Promise<AuthUser | null>;
  resetPassword(email: string): Promise<void>;
  updatePassword(userId: string, newPassword: string): Promise<void>;
}

// ---------------------------------------------------------------------------
// BATCH CONVERSION ENGINE
// ---------------------------------------------------------------------------

export interface BatchJob {
  id: string;
  userId?: string;
  files: Array<{
    id: string;
    file: File;
    status: 'pending' | 'processing' | 'completed' | 'failed';
    result?: ConversionResult;
    error?: string;
  }>;
  options: Record<string, unknown>;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'partial';
  createdAt: Date;
  completedAt?: Date;
}

export interface IBatchEngine {
  createBatch(files: File[], options: Record<string, unknown>): Promise<BatchJob>;
  getBatch(id: string): Promise<BatchJob | null>;
  processBatch(id: string, onProgress?: (progress: ConversionProgress) => void): Promise<BatchJob>;
  cancelBatch(id: string): Promise<void>;
  getResults(id: string): Promise<ConversionResult[]>;
  downloadAll(id: string): Promise<Blob>;
}

// ---------------------------------------------------------------------------
// QUEUE SYSTEM
// ---------------------------------------------------------------------------

export interface QueueJob {
  id: string;
  type: string;
  payload: Record<string, unknown>;
  priority: 'low' | 'normal' | 'high';
  status: 'pending' | 'processing' | 'completed' | 'failed';
  attempts: number;
  maxAttempts: number;
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;
  error?: string;
}

export interface IQueueEngine {
  enqueue(type: string, payload: Record<string, unknown>, priority?: 'low' | 'normal' | 'high'): Promise<QueueJob>;
  dequeue(): Promise<QueueJob | null>;
  complete(id: string): Promise<void>;
  fail(id: string, error: string): Promise<void>;
  retry(id: string): Promise<void>;
  getStats(): Promise<{ pending: number; processing: number; completed: number; failed: number }>;
}

// ---------------------------------------------------------------------------
// API PLATFORM
// ---------------------------------------------------------------------------

export interface ApiKey {
  id: string;
  userId: string;
  key: string;
  name: string;
  permissions: string[];
  rateLimit: number;
  usage: number;
  lastUsed?: Date;
  createdAt: Date;
  expiresAt?: Date;
}

export interface ApiUsage {
  keyId: string;
  date: Date;
  requests: number;
  bytesIn: number;
  bytesOut: number;
}

export interface IApiEngine {
  createKey(userId: string, name: string, permissions: string[]): Promise<ApiKey>;
  getKey(key: string): Promise<ApiKey | null>;
  revokeKey(id: string): Promise<void>;
  validateKey(key: string, permission: string): Promise<boolean>;
  recordUsage(keyId: string, bytesIn: number, bytesOut: number): Promise<void>;
  getUsage(keyId: string, period?: { start: Date; end: Date }): Promise<ApiUsage[]>;
}

// ---------------------------------------------------------------------------
// SAAS FEATURES ENGINE
// ---------------------------------------------------------------------------

export interface Workspace {
  id: string;
  name: string;
  ownerId: string;
  members: Array<{
    userId: string;
    role: 'owner' | 'admin' | 'member';
  }>;
  settings: Record<string, unknown>;
  createdAt: Date;
}

export interface TeamInvite {
  id: string;
  workspaceId: string;
  email: string;
  role: 'admin' | 'member';
  token: string;
  expiresAt: Date;
  createdAt: Date;
}

export interface ISaasEngine {
  createWorkspace(userId: string, name: string): Promise<Workspace>;
  getWorkspace(id: string): Promise<Workspace | null>;
  inviteMember(workspaceId: string, email: string, role: string): Promise<TeamInvite>;
  acceptInvite(token: string): Promise<Workspace>;
  removeMember(workspaceId: string, userId: string): Promise<void>;
  updateSettings(workspaceId: string, settings: Record<string, unknown>): Promise<void>;
}

// ---------------------------------------------------------------------------
// SERVICE REGISTRY
// ---------------------------------------------------------------------------

export interface ServiceRegistry {
  longTail?: ILongTailEngine;
  seo?: ISeoEngine;
  premium?: IPremiumEngine;
  download?: IDownloadEngine;
  limits?: ILimitsEngine;
  ads?: IAdsEngine;
  auth?: IAuthEngine;
  batch?: IBatchEngine;
  queue?: IQueueEngine;
  api?: IApiEngine;
  saas?: ISaasEngine;
}

// Placeholder for future implementation
export const futureServices: ServiceRegistry = {};
