/**
 * lib/registry/format-registry.ts
 * Central format registry - single source of truth for all supported formats
 */

import type {
  FormatDefinition,
  FormatCategory,
  FormatTier,
  ProcessingEngine,
  CategoryDefinition,
  ViewerEngine,
} from '../types/formats';
import type { LucideIcon } from 'lucide-react';
import {
  FileImage,
  Film,
  Music,
  FileText,
  Cuboid,
  Layers,
  Archive,
  Type,
  Map as MapIcon,
  Mail,
  Code,
  BookOpen,
} from 'lucide-react';

// ---------------------------------------------------------------------------
// CATEGORY DEFINITIONS
// ---------------------------------------------------------------------------

export const CATEGORY_DEFINITIONS: Record<FormatCategory, CategoryDefinition> = {
  image: {
    label: "Raster Image",
    icon: FileImage,
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
    gradient: ["from-emerald-500", "to-teal-500"],
    seoLabel: "Image",
    converterRoute: "/image-converter",
    hasViewer: true,
    hasEditor: true,
  },
  raw: {
    label: "Camera RAW",
    icon: FileImage,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    gradient: ["from-amber-500", "to-orange-500"],
    seoLabel: "Camera RAW",
    converterRoute: "/image-converter",
    hasViewer: true,
    hasEditor: false,
  },
  vector: {
    label: "Vector / Design",
    icon: Layers,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
    gradient: ["from-blue-500", "to-cyan-500"],
    seoLabel: "Vector",
    converterRoute: "/image-converter",
    hasViewer: true,
    hasEditor: true,
  },
  icon: {
    label: "Icon",
    icon: FileImage,
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    gradient: ["from-slate-500", "to-slate-700"],
    seoLabel: "Icon",
    converterRoute: "/image-converter",
    hasViewer: true,
    hasEditor: false,
  },
  cad: {
    label: "CAD / 3D",
    icon: Cuboid,
    color: "text-cyan-600",
    bgColor: "bg-cyan-50",
    gradient: ["from-cyan-500", "to-blue-500"],
    seoLabel: "CAD",
    converterRoute: "/cad-converter",
    hasViewer: true,
    hasEditor: false,
  },
  video: {
    label: "Video",
    icon: Film,
    color: "text-violet-600",
    bgColor: "bg-violet-50",
    gradient: ["from-violet-500", "to-purple-500"],
    seoLabel: "Video",
    converterRoute: "/video-converter",
    hasViewer: true,
    hasEditor: true,
  },
  audio: {
    label: "Audio",
    icon: Music,
    color: "text-rose-600",
    bgColor: "bg-rose-50",
    gradient: ["from-rose-500", "to-pink-500"],
    seoLabel: "Audio",
    converterRoute: "/audio-converter",
    hasViewer: true,
    hasEditor: true,
  },
  document: {
    label: "Document",
    icon: FileText,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    gradient: ["from-amber-500", "to-orange-500"],
    seoLabel: "Document",
    converterRoute: "/document-converter",
    hasViewer: true,
    hasEditor: true,
  },
  archive: {
    label: "Archive",
    icon: Archive,
    color: "text-stone-600",
    bgColor: "bg-stone-50",
    gradient: ["from-stone-500", "to-stone-700"],
    seoLabel: "Archive",
    converterRoute: "/archive-converter",
    hasViewer: true,
    hasEditor: false,
  },
  font: {
    label: "Font",
    icon: Type,
    color: "text-indigo-600",
    bgColor: "bg-indigo-50",
    gradient: ["from-indigo-500", "to-violet-500"],
    seoLabel: "Font",
    converterRoute: "/font-converter",
    hasViewer: true,
    hasEditor: false,
  },
  gis: {
    label: "GIS / Geo",
    icon: MapIcon,
    color: "text-green-600",
    bgColor: "bg-green-50",
    gradient: ["from-green-500", "to-emerald-500"],
    seoLabel: "GIS",
    converterRoute: "/gis-converter",
    hasViewer: true,
    hasEditor: false,
  },
  email: {
    label: "Email",
    icon: Mail,
    color: "text-sky-600",
    bgColor: "bg-sky-50",
    gradient: ["from-sky-500", "to-cyan-500"],
    seoLabel: "Email",
    hasViewer: true,
    hasEditor: false,
  },
  code: {
    label: "Code / Data",
    icon: Code,
    color: "text-slate-600",
    bgColor: "bg-slate-50",
    gradient: ["from-slate-500", "to-gray-600"],
    seoLabel: "Code",
    hasViewer: true,
    hasEditor: true,
  },
  ebook: {
    label: "eBook",
    icon: BookOpen,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
    gradient: ["from-amber-500", "to-yellow-500"],
    seoLabel: "eBook",
    converterRoute: "/ebook-converter",
    hasViewer: true,
    hasEditor: false,
  },
};

// ---------------------------------------------------------------------------
// FORMAT DEFINITIONS
// ---------------------------------------------------------------------------

export const FORMAT_DEFINITIONS: FormatDefinition[] = [
  // ── Raster Image ────────────────────────────────────────────────────────────
  {
    ext: "png",
    name: "PNG Image",
    category: "image",
    mime: "image/png",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Lossless raster image with full transparency support",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 100,
    searchVolume: 500000,
    popularConversions: ["jpg", "webp", "gif", "pdf", "svg"],
  },
  {
    ext: "jpg",
    name: "JPEG Image",
    category: "image",
    mime: "image/jpeg",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Widely-supported lossy compressed photo format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 100,
    searchVolume: 450000,
    popularConversions: ["png", "webp", "pdf", "gif"],
  },
  {
    ext: "jpeg",
    name: "JPEG Image",
    category: "image",
    mime: "image/jpeg",
    tier: "standard",
    engine: "canvas",
    browserNative: true,
    description: "Full extension alias for the JPG format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true },
    supportsBatch: true,
    searchPriority: 80,
    popularConversions: ["png", "webp", "pdf"],
  },
  {
    ext: "webp",
    name: "WebP Image",
    category: "image",
    mime: "image/webp",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Modern web format with superior compression over JPEG/PNG",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 95,
    searchVolume: 300000,
    popularConversions: ["png", "jpg", "gif"],
  },
  {
    ext: "gif",
    name: "GIF Image",
    category: "image",
    mime: "image/gif",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Supports animation; limited 256-color palette",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 90,
    searchVolume: 250000,
    popularConversions: ["mp4", "webp", "png", "jpg"],
  },
  {
    ext: "bmp",
    name: "Bitmap Image",
    category: "image",
    mime: "image/bmp",
    tier: "standard",
    engine: "canvas",
    browserNative: true,
    description: "Uncompressed raster format — large file size",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["png", "jpg", "webp"],
  },
  {
    ext: "tiff",
    name: "TIFF Image",
    category: "image",
    mime: "image/tiff",
    tier: "standard",
    engine: "canvas",
    description: "High-quality image format favored in print and publishing",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 75,
    searchVolume: 50000,
    popularConversions: ["pdf", "png", "jpg"],
  },
  {
    ext: "heic",
    name: "HEIC Image",
    category: "image",
    mime: "image/heic",
    tier: "popular",
    engine: "canvas",
    description: "Apple High Efficiency Image Container — default on iOS",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 90,
    searchVolume: 200000,
    popularConversions: ["jpg", "png", "webp"],
  },
  {
    ext: "heif",
    name: "HEIF Image",
    category: "image",
    mime: "image/heif",
    tier: "standard",
    engine: "canvas",
    description: "High Efficiency Image File — HEVC-compressed container",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 60,
    popularConversions: ["jpg", "png", "webp"],
  },
  {
    ext: "avif",
    name: "AVIF Image",
    category: "image",
    mime: "image/avif",
    tier: "standard",
    engine: "canvas",
    browserNative: true,
    description: "AV1 Image Format — next-gen compression",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 85,
    searchVolume: 100000,
    popularConversions: ["png", "jpg", "webp"],
  },

  // ── Camera RAW ──────────────────────────────────────────────────────────────
  {
    ext: "raw",
    name: "RAW Image",
    category: "raw",
    mime: "image/raw",
    tier: "standard",
    engine: "canvas",
    description: "Generic unprocessed camera sensor data file",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 50,
    popularConversions: ["jpg", "png", "tiff"],
  },
  {
    ext: "cr2",
    name: "Canon RAW",
    category: "raw",
    mime: "image/x-canon-cr2",
    tier: "popular",
    engine: "canvas",
    description: "Canon Camera RAW 2 format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["jpg", "png", "tiff"],
  },
  {
    ext: "nef",
    name: "Nikon RAW",
    category: "raw",
    mime: "image/x-nikon-nef",
    tier: "popular",
    engine: "canvas",
    description: "Nikon Electronic Format — RAW sensor data",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["jpg", "png", "tiff"],
  },
  {
    ext: "arw",
    name: "Sony RAW",
    category: "raw",
    mime: "image/x-sony-arw",
    tier: "popular",
    engine: "canvas",
    description: "Sony Alpha RAW format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["jpg", "png", "tiff"],
  },
  {
    ext: "dng",
    name: "Adobe DNG",
    category: "raw",
    mime: "image/x-adobe-dng",
    tier: "standard",
    engine: "canvas",
    description: "Adobe Digital Negative — open universal RAW standard",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 65,
    popularConversions: ["jpg", "png", "tiff"],
  },

  // ── Vector & Design ─────────────────────────────────────────────────────────
  {
    ext: "svg",
    name: "SVG Vector",
    category: "vector",
    mime: "image/svg+xml",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Scalable Vector Graphics — XML-based, resolution-independent",
    viewerEngine: "svg",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 90,
    searchVolume: 150000,
    popularConversions: ["png", "jpg", "pdf"],
  },
  {
    ext: "ai",
    name: "Adobe Illustrator",
    category: "vector",
    mime: "application/postscript",
    tier: "standard",
    engine: "server",
    description: "Adobe Illustrator native vector format",
    viewerEngine: "none",
    hasViewer: false,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 75,
    popularConversions: ["svg", "eps", "png", "pdf"],
  },
  {
    ext: "eps",
    name: "EPS Vector",
    category: "vector",
    mime: "application/postscript",
    tier: "standard",
    engine: "server",
    description: "Encapsulated PostScript — universal vector interchange",
    viewerEngine: "none",
    hasViewer: false,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 60,
    popularConversions: ["svg", "png", "pdf"],
  },
  {
    ext: "psd",
    name: "Photoshop Document",
    category: "vector",
    mime: "image/vnd.adobe.photoshop",
    tier: "popular",
    engine: "server",
    description: "Adobe Photoshop layered document",
    viewerEngine: "psd",
    hasViewer: true,
    editorCapability: "basic",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 85,
    searchVolume: 180000,
    popularConversions: ["png", "jpg", "pdf"],
  },
  {
    ext: "cdr",
    name: "CorelDRAW",
    category: "vector",
    mime: "application/x-cdr",
    tier: "advanced",
    engine: "server",
    description: "CorelDRAW native vector format",
    viewerEngine: "none",
    hasViewer: false,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 50,
    popularConversions: ["svg", "png", "pdf"],
  },
  {
    ext: "indd",
    name: "InDesign Document",
    category: "vector",
    mime: "application/x-indesign",
    tier: "advanced",
    engine: "server",
    description: "Adobe InDesign page-layout document",
    viewerEngine: "none",
    hasViewer: false,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 45,
    popularConversions: ["pdf", "jpg", "png"],
  },

  // ── Icons ───────────────────────────────────────────────────────────────────
  {
    ext: "ico",
    name: "Windows Icon",
    category: "icon",
    mime: "image/x-icon",
    tier: "popular",
    engine: "canvas",
    browserNative: true,
    description: "Windows multi-resolution icon format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 80,
    searchVolume: 100000,
    popularConversions: ["png", "icns"],
  },
  {
    ext: "icns",
    name: "Apple Icon",
    category: "icon",
    mime: "image/x-icns",
    tier: "standard",
    engine: "canvas",
    description: "macOS multi-resolution icon format",
    viewerEngine: "native-image",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["png", "ico"],
  },

  // ── CAD / 3D ────────────────────────────────────────────────────────────────
  {
    ext: "dwg",
    name: "AutoCAD Drawing",
    category: "cad",
    mime: "application/acad",
    tier: "popular",
    engine: "server",
    description: "AutoCAD native binary drawing format",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 80,
    searchVolume: 120000,
    popularConversions: ["dxf", "pdf"],
  },
  {
    ext: "dxf",
    name: "CAD Exchange Format",
    category: "cad",
    mime: "application/dxf",
    tier: "popular",
    engine: "server",
    description: "Drawing Exchange Format — universal CAD interchange",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true },
    supportsBatch: false,
    searchPriority: 75,
    searchVolume: 80000,
    popularConversions: ["dwg", "pdf", "svg"],
  },
  {
    ext: "step",
    name: "STEP 3D Model",
    category: "cad",
    mime: "application/step",
    tier: "popular",
    engine: "server",
    description: "ISO 10303 STEP — industry-standard 3D exchange format",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 70,
    popularConversions: ["stl", "obj"],
  },
  {
    ext: "stp",
    name: "STEP 3D Model",
    category: "cad",
    mime: "application/step",
    tier: "standard",
    engine: "server",
    description: "Alternate .stp extension for STEP 3D files",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 55,
    popularConversions: ["stl", "obj"],
  },
  {
    ext: "stl",
    name: "STL 3D Model",
    category: "cad",
    mime: "model/stl",
    tier: "popular",
    engine: "server",
    description: "Stereolithography format — 3D printing standard",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 75,
    searchVolume: 90000,
    popularConversions: ["obj", "step"],
  },
  {
    ext: "obj",
    name: "OBJ 3D Model",
    category: "cad",
    mime: "model/obj",
    tier: "standard",
    engine: "server",
    description: "Wavefront OBJ — widely-supported 3D mesh format",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 65,
    popularConversions: ["stl", "fbx", "step"],
  },
  {
    ext: "fbx",
    name: "FBX 3D Model",
    category: "cad",
    mime: "application/octet-stream",
    tier: "standard",
    engine: "server",
    description: "Autodesk FBX — animation-capable 3D interchange",
    viewerEngine: "cad",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 60,
    popularConversions: ["obj", "stl"],
  },

  // ── Video ──────────────────────────────────────────────────────────────────
  {
    ext: "mp4",
    name: "MP4 Video",
    category: "video",
    mime: "video/mp4",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "H.264/MPEG-4 — the universal video container standard",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 100,
    searchVolume: 400000,
    popularConversions: ["webm", "avi", "mov", "gif", "mp3"],
  },
  {
    ext: "webm",
    name: "WebM Video",
    category: "video",
    mime: "video/webm",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Open web video format optimized for streaming",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 90,
    searchVolume: 150000,
    popularConversions: ["mp4", "avi", "gif"],
  },
  {
    ext: "avi",
    name: "AVI Video",
    category: "video",
    mime: "video/x-msvideo",
    tier: "popular",
    engine: "ffmpeg",
    description: "Audio Video Interleave — classic Windows container",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 85,
    searchVolume: 120000,
    popularConversions: ["mp4", "webm", "mov"],
  },
  {
    ext: "mov",
    name: "QuickTime Movie",
    category: "video",
    mime: "video/quicktime",
    tier: "popular",
    engine: "ffmpeg",
    description: "Apple QuickTime video container",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 85,
    searchVolume: 130000,
    popularConversions: ["mp4", "webm", "avi"],
  },
  {
    ext: "mkv",
    name: "Matroska Video",
    category: "video",
    mime: "video/x-matroska",
    tier: "popular",
    engine: "ffmpeg",
    description: "Open multimedia container supporting all codecs",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 80,
    searchVolume: 100000,
    popularConversions: ["mp4", "webm", "avi"],
  },
  {
    ext: "wmv",
    name: "Windows Media Video",
    category: "video",
    mime: "video/x-ms-wmv",
    tier: "standard",
    engine: "ffmpeg",
    description: "Microsoft Windows Media Video format",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 70,
    popularConversions: ["mp4", "webm", "avi"],
  },
  {
    ext: "flv",
    name: "Flash Video",
    category: "video",
    mime: "video/x-flv",
    tier: "standard",
    engine: "ffmpeg",
    description: "Adobe Flash Video — legacy streaming format",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 55,
    tags: ["legacy"],
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "mpeg",
    name: "MPEG Video",
    category: "video",
    mime: "video/mpeg",
    tier: "standard",
    engine: "ffmpeg",
    description: "MPEG-1/2 video — classic DVD and VCD format",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 60,
    tags: ["legacy"],
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "mpg",
    name: "MPG Video",
    category: "video",
    mime: "video/mpeg",
    tier: "standard",
    engine: "ffmpeg",
    description: "Short-extension alias for MPEG-1/2 video",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 50,
    tags: ["legacy"],
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "m4v",
    name: "M4V Video",
    category: "video",
    mime: "video/x-m4v",
    tier: "popular",
    engine: "ffmpeg",
    description: "iTunes video format — optional DRM variant of MP4",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 75,
    popularConversions: ["mp4", "webm", "avi"],
  },
  {
    ext: "3gp",
    name: "3GP Video",
    category: "video",
    mime: "video/3gpp",
    tier: "standard",
    engine: "ffmpeg",
    description: "3GPP mobile video — designed for older mobile phones",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 55,
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "ogv",
    name: "OGV Video",
    category: "video",
    mime: "video/ogg",
    tier: "standard",
    engine: "ffmpeg",
    browserNative: true,
    description: "Ogg Video — open-source Theora video in Ogg container",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 50,
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "ts",
    name: "MPEG-TS Video",
    category: "video",
    mime: "video/mp2t",
    tier: "advanced",
    engine: "ffmpeg",
    description: "MPEG Transport Stream — broadcast and HLS segment format",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: false,
    searchPriority: 45,
    popularConversions: ["mp4", "webm"],
  },
  {
    ext: "f4v",
    name: "F4V Video",
    category: "video",
    mime: "video/x-f4v",
    tier: "advanced",
    engine: "ffmpeg",
    description: "Flash MP4 Video — H.264 inside a Flash container",
    viewerEngine: "video",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 40,
    tags: ["legacy"],
    popularConversions: ["mp4", "webm"],
  },

  // ── Audio ──────────────────────────────────────────────────────────────────
  {
    ext: "mp3",
    name: "MP3 Audio",
    category: "audio",
    mime: "audio/mpeg",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "MPEG Layer 3 — the universal compressed audio format",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 100,
    searchVolume: 350000,
    popularConversions: ["wav", "flac", "aac", "ogg"],
  },
  {
    ext: "wav",
    name: "WAV Audio",
    category: "audio",
    mime: "audio/wav",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Uncompressed PCM audio — bit-perfect quality",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 90,
    searchVolume: 180000,
    popularConversions: ["mp3", "flac", "aac"],
  },
  {
    ext: "ogg",
    name: "Ogg Vorbis",
    category: "audio",
    mime: "audio/ogg",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Open-source compressed audio with excellent quality/size",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 80,
    searchVolume: 100000,
    popularConversions: ["mp3", "wav", "flac"],
  },
  {
    ext: "flac",
    name: "FLAC Audio",
    category: "audio",
    mime: "audio/flac",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Free Lossless Audio Codec — perfect reconstruction",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 85,
    searchVolume: 150000,
    tags: ["lossless"],
    popularConversions: ["mp3", "wav", "aac"],
  },
  {
    ext: "aac",
    name: "AAC Audio",
    category: "audio",
    mime: "audio/aac",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Advanced Audio Coding — successor to MP3 at lower bitrates",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 85,
    searchVolume: 120000,
    popularConversions: ["mp3", "wav", "m4a"],
  },
  {
    ext: "m4a",
    name: "M4A Audio",
    category: "audio",
    mime: "audio/mp4",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "AAC audio in MPEG-4 container — iTunes and Apple default",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 80,
    searchVolume: 110000,
    popularConversions: ["mp3", "wav", "aac"],
  },
  {
    ext: "wma",
    name: "Windows Media Audio",
    category: "audio",
    mime: "audio/x-ms-wma",
    tier: "standard",
    engine: "ffmpeg",
    description: "Microsoft Windows Media Audio format",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 60,
    popularConversions: ["mp3", "wav", "aac"],
  },
  {
    ext: "aiff",
    name: "AIFF Audio",
    category: "audio",
    mime: "audio/aiff",
    tier: "standard",
    engine: "ffmpeg",
    description: "Apple Interchange File Format — uncompressed audio",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 55,
    tags: ["lossless"],
    popularConversions: ["mp3", "wav", "flac"],
  },
  {
    ext: "opus",
    name: "Opus Audio",
    category: "audio",
    mime: "audio/opus",
    tier: "popular",
    engine: "ffmpeg",
    browserNative: true,
    description: "Modern low-latency codec by Xiph — best quality-to-size ratio",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 75,
    searchVolume: 80000,
    popularConversions: ["mp3", "wav", "ogg"],
  },
  {
    ext: "ac3",
    name: "AC3 Audio",
    category: "audio",
    mime: "audio/ac3",
    tier: "standard",
    engine: "ffmpeg",
    description: "Dolby Digital — multichannel surround sound for DVD/Blu-ray",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 55,
    popularConversions: ["mp3", "wav", "aac"],
  },
  {
    ext: "amr",
    name: "AMR Audio",
    category: "audio",
    mime: "audio/amr",
    tier: "standard",
    engine: "ffmpeg",
    description: "Adaptive Multi-Rate — mobile voice recording codec",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 50,
    popularConversions: ["mp3", "wav"],
  },
  {
    ext: "caf",
    name: "Core Audio Format",
    category: "audio",
    mime: "audio/x-caf",
    tier: "standard",
    engine: "ffmpeg",
    description: "Apple Core Audio Format — supports files over 4 GB",
    viewerEngine: "audio",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, ffmpeg: true },
    supportsBatch: true,
    searchPriority: 45,
    popularConversions: ["mp3", "wav", "aac"],
  },

  // ── Document ────────────────────────────────────────────────────────────────
  {
    ext: "pdf",
    name: "PDF Document",
    category: "document",
    mime: "application/pdf",
    tier: "popular",
    engine: "pdf-lib",
    browserNative: true,
    description: "Portable Document Format — universal fixed-layout document",
    viewerEngine: "pdf",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: true,
    searchPriority: 100,
    searchVolume: 500000,
    popularConversions: ["jpg", "png", "docx", "txt"],
  },
  {
    ext: "doc",
    name: "Word Document",
    category: "document",
    mime: "application/msword",
    tier: "popular",
    engine: "server",
    description: "Microsoft Word 97–2003 binary format",
    viewerEngine: "docx",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 85,
    searchVolume: 200000,
    popularConversions: ["docx", "pdf", "txt"],
  },
  {
    ext: "docx",
    name: "Word Document (OOXML)",
    category: "document",
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    tier: "popular",
    engine: "native",
    description: "Microsoft Word Open XML — current default format",
    viewerEngine: "docx",
    hasViewer: true,
    editorCapability: "basic",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 90,
    searchVolume: 250000,
    popularConversions: ["pdf", "doc", "txt", "html"],
  },
  {
    ext: "xls",
    name: "Excel Spreadsheet",
    category: "document",
    mime: "application/vnd.ms-excel",
    tier: "popular",
    engine: "native",
    description: "Microsoft Excel 97–2003 binary spreadsheet",
    viewerEngine: "spreadsheet",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 80,
    searchVolume: 150000,
    popularConversions: ["xlsx", "pdf", "csv"],
  },
  {
    ext: "xlsx",
    name: "Excel (OOXML)",
    category: "document",
    mime: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    tier: "popular",
    engine: "native",
    description: "Microsoft Excel Open XML — current default format",
    viewerEngine: "spreadsheet",
    hasViewer: true,
    editorCapability: "basic",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 85,
    searchVolume: 180000,
    popularConversions: ["pdf", "xls", "csv"],
  },
  {
    ext: "ppt",
    name: "PowerPoint",
    category: "document",
    mime: "application/vnd.ms-powerpoint",
    tier: "popular",
    engine: "native",
    description: "Microsoft PowerPoint 97–2003 binary format",
    viewerEngine: "pptx",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 75,
    searchVolume: 100000,
    popularConversions: ["pptx", "pdf"],
  },
  {
    ext: "pptx",
    name: "PowerPoint (OOXML)",
    category: "document",
    mime: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    tier: "popular",
    engine: "native",
    description: "Microsoft PowerPoint Open XML format",
    viewerEngine: "pptx",
    hasViewer: true,
    editorCapability: "basic",
    providers: { serverSide: true, libreOffice: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 80,
    searchVolume: 120000,
    popularConversions: ["pdf", "ppt"],
  },
  {
    ext: "txt",
    name: "Plain Text",
    category: "document",
    mime: "text/plain",
    tier: "popular",
    engine: "native",
    browserNative: true,
    description: "Unformatted plain text — universally readable",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 70,
    searchVolume: 80000,
    popularConversions: ["pdf", "docx", "html"],
  },
  {
    ext: "rtf",
    name: "Rich Text Format",
    category: "document",
    mime: "application/rtf",
    tier: "standard",
    engine: "native",
    description: "Rich Text Format — cross-application formatted text",
    viewerEngine: "docx",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true },
    supportsBatch: false,
    searchPriority: 55,
    popularConversions: ["pdf", "docx", "txt"],
  },
  {
    ext: "odt",
    name: "OpenDocument Text",
    category: "document",
    mime: "application/vnd.oasis.opendocument.text",
    tier: "standard",
    engine: "native",
    description: "LibreOffice / OpenOffice Writer text document",
    viewerEngine: "docx",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true },
    supportsBatch: false,
    searchPriority: 60,
    popularConversions: ["docx", "pdf", "txt"],
  },
  {
    ext: "ods",
    name: "OpenDocument Sheet",
    category: "document",
    mime: "application/vnd.oasis.opendocument.spreadsheet",
    tier: "standard",
    engine: "native",
    description: "LibreOffice / OpenOffice Calc spreadsheet",
    viewerEngine: "spreadsheet",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true },
    supportsBatch: false,
    searchPriority: 55,
    popularConversions: ["xlsx", "pdf", "csv"],
  },
  {
    ext: "odp",
    name: "OpenDocument Slides",
    category: "document",
    mime: "application/vnd.oasis.opendocument.presentation",
    tier: "standard",
    engine: "native",
    description: "LibreOffice / OpenOffice Impress presentation",
    viewerEngine: "pptx",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, libreOffice: true },
    supportsBatch: false,
    searchPriority: 50,
    popularConversions: ["pptx", "pdf"],
  },
  {
    ext: "html",
    name: "HTML Document",
    category: "document",
    mime: "text/html",
    tier: "standard",
    engine: "native",
    browserNative: true,
    description: "HyperText Markup Language — web page source",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 65,
    popularConversions: ["pdf", "txt", "md"],
  },
  {
    ext: "md",
    name: "Markdown Document",
    category: "document",
    mime: "text/markdown",
    tier: "standard",
    engine: "native",
    description: "Lightweight markup language for formatted plain text",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 60,
    popularConversions: ["pdf", "html", "docx"],
  },

  // ── eBook ──────────────────────────────────────────────────────────────────
  {
    ext: "epub",
    name: "EPUB eBook",
    category: "ebook",
    mime: "application/epub+zip",
    tier: "popular",
    engine: "jszip",
    description: "Open eBook standard — compatible with most e-readers",
    viewerEngine: "ebook",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 80,
    searchVolume: 100000,
    tags: ["ebook"],
    popularConversions: ["pdf", "mobi", "txt"],
  },
  {
    ext: "mobi",
    name: "Mobipocket eBook",
    category: "ebook",
    mime: "application/x-mobipocket-ebook",
    tier: "standard",
    engine: "native",
    description: "Mobipocket eBook — used by older Kindle devices",
    viewerEngine: "ebook",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 65,
    tags: ["ebook"],
    popularConversions: ["epub", "pdf", "azw3"],
  },
  {
    ext: "azw3",
    name: "Kindle eBook",
    category: "ebook",
    mime: "application/vnd.amazon.ebook",
    tier: "popular",
    engine: "native",
    description: "Amazon Kindle Format 8 — modern Kindle default",
    viewerEngine: "ebook",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 70,
    tags: ["ebook"],
    popularConversions: ["epub", "pdf", "mobi"],
  },

  // ── Archive ────────────────────────────────────────────────────────────────
  {
    ext: "zip",
    name: "ZIP Archive",
    category: "archive",
    mime: "application/zip",
    tier: "popular",
    engine: "jszip",
    browserNative: false,
    description: "Standard compressed archive format",
    viewerEngine: "archive",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 80,
    searchVolume: 150000,
    popularConversions: ["rar", "7z"],
  },
  {
    ext: "rar",
    name: "RAR Archive",
    category: "archive",
    mime: "application/vnd.rar",
    tier: "popular",
    engine: "archive-engine",
    description: "RAR compressed archive",
    viewerEngine: "archive",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 75,
    searchVolume: 100000,
    popularConversions: ["zip", "7z"],
  },
  {
    ext: "7z",
    name: "7-Zip Archive",
    category: "archive",
    mime: "application/x-7z-compressed",
    tier: "popular",
    engine: "archive-engine",
    description: "7-Zip compressed archive with high compression ratio",
    viewerEngine: "archive",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true },
    supportsBatch: false,
    searchPriority: 70,
    searchVolume: 80000,
    popularConversions: ["zip", "rar"],
  },
  {
    ext: "tar",
    name: "TAR Archive",
    category: "archive",
    mime: "application/x-tar",
    tier: "standard",
    engine: "archive-engine",
    description: "Unix tape archive format",
    viewerEngine: "archive",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 55,
    popularConversions: ["zip", "gz"],
  },
  {
    ext: "gz",
    name: "GZIP Archive",
    category: "archive",
    mime: "application/gzip",
    tier: "standard",
    engine: "archive-engine",
    description: "GNU zip compressed file",
    viewerEngine: "archive",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 50,
    popularConversions: ["zip"],
  },

  // ── Font ───────────────────────────────────────────────────────────────────
  {
    ext: "ttf",
    name: "TrueType Font",
    category: "font",
    mime: "font/ttf",
    tier: "popular",
    engine: "font-engine",
    description: "TrueType scalable font format",
    viewerEngine: "font",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 65,
    searchVolume: 50000,
    popularConversions: ["woff", "woff2", "otf"],
  },
  {
    ext: "otf",
    name: "OpenType Font",
    category: "font",
    mime: "font/otf",
    tier: "popular",
    engine: "font-engine",
    description: "OpenType scalable font format",
    viewerEngine: "font",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 60,
    searchVolume: 40000,
    popularConversions: ["ttf", "woff", "woff2"],
  },
  {
    ext: "woff",
    name: "Web Open Font Format",
    category: "font",
    mime: "font/woff",
    tier: "popular",
    engine: "font-engine",
    description: "Web-optimized font format",
    viewerEngine: "font",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 70,
    searchVolume: 60000,
    popularConversions: ["ttf", "otf", "woff2"],
  },
  {
    ext: "woff2",
    name: "Web Open Font Format 2",
    category: "font",
    mime: "font/woff2",
    tier: "popular",
    engine: "font-engine",
    description: "Next-gen web font format with better compression",
    viewerEngine: "font",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 75,
    searchVolume: 70000,
    popularConversions: ["ttf", "otf", "woff"],
  },

  // ── Email ──────────────────────────────────────────────────────────────────
  {
    ext: "eml",
    name: "Email Message",
    category: "email",
    mime: "message/rfc822",
    tier: "standard",
    engine: "native",
    description: "Email message format",
    viewerEngine: "email",
    hasViewer: true,
    editorCapability: "none",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 55,
    popularConversions: ["pdf", "txt", "html"],
  },
  {
    ext: "msg",
    name: "Outlook Message",
    category: "email",
    mime: "application/vnd.ms-outlook",
    tier: "standard",
    engine: "server",
    description: "Microsoft Outlook email message",
    viewerEngine: "email",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 50,
    popularConversions: ["eml", "pdf"],
  },

  // ── Code / Data ────────────────────────────────────────────────────────────
  {
    ext: "json",
    name: "JSON Data",
    category: "code",
    mime: "application/json",
    tier: "popular",
    engine: "native",
    description: "JavaScript Object Notation data format",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 70,
    searchVolume: 60000,
    popularConversions: ["xml", "csv"],
  },
  {
    ext: "xml",
    name: "XML Document",
    category: "code",
    mime: "application/xml",
    tier: "standard",
    engine: "native",
    description: "Extensible Markup Language document",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 60,
    popularConversions: ["json", "html"],
  },
  {
    ext: "csv",
    name: "CSV Data",
    category: "code",
    mime: "text/csv",
    tier: "popular",
    engine: "native",
    description: "Comma-Separated Values data",
    viewerEngine: "spreadsheet",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 75,
    searchVolume: 90000,
    popularConversions: ["xlsx", "json", "xml"],
  },
  {
    ext: "yaml",
    name: "YAML Config",
    category: "code",
    mime: "application/yaml",
    tier: "standard",
    engine: "native",
    description: "YAML configuration format",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 55,
    popularConversions: ["json", "xml"],
  },
  {
    ext: "sql",
    name: "SQL Script",
    category: "code",
    mime: "application/sql",
    tier: "standard",
    engine: "native",
    description: "SQL database script",
    viewerEngine: "text",
    hasViewer: true,
    editorCapability: "full",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: true,
    searchPriority: 50,
    popularConversions: ["csv", "json"],
  },

  // ── GIS ────────────────────────────────────────────────────────────────────
  {
    ext: "geojson",
    name: "GeoJSON",
    category: "gis",
    mime: "application/geo+json",
    tier: "popular",
    engine: "gis-engine",
    description: "Geographic JSON format for mapping data",
    viewerEngine: "gis",
    hasViewer: true,
    editorCapability: "basic",
    providers: { clientSide: true, serverSide: true },
    supportsBatch: false,
    searchPriority: 60,
    searchVolume: 30000,
    popularConversions: ["kml", "shp"],
  },
  {
    ext: "kml",
    name: "KML Document",
    category: "gis",
    mime: "application/vnd.google-earth.kml+xml",
    tier: "popular",
    engine: "gis-engine",
    description: "Keyhole Markup Language for geographic data",
    viewerEngine: "gis",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true },
    supportsBatch: false,
    searchPriority: 55,
    searchVolume: 25000,
    popularConversions: ["geojson", "shp"],
  },
  {
    ext: "shp",
    name: "Shapefile",
    category: "gis",
    mime: "application/x-shp",
    tier: "standard",
    engine: "gis-engine",
    description: "ESRI Shapefile geographic format",
    viewerEngine: "gis",
    hasViewer: true,
    editorCapability: "none",
    providers: { serverSide: true, premiumApi: true },
    supportsBatch: false,
    searchPriority: 50,
    popularConversions: ["geojson", "kml"],
  },
];

// ---------------------------------------------------------------------------
// REGISTRY CLASS
// ---------------------------------------------------------------------------

class FormatRegistry {
  private formatMap: Map<string, FormatDefinition> = new Map();
  private categoryFormats: Map<FormatCategory, FormatDefinition[]> = new Map();
  private viewerFormats: Map<string, FormatDefinition[]> = new Map();
  private editorFormats: Map<string, FormatDefinition[]> = new Map();

  constructor() {
    // Populate format map
    for (const f of FORMAT_DEFINITIONS) {
      this.formatMap.set(f.ext.toLowerCase(), f);
    }

    for (const fmt of FORMAT_DEFINITIONS) {
      // Category groupings
      const catList = this.categoryFormats.get(fmt.category) || [];
      catList.push(fmt);
      this.categoryFormats.set(fmt.category, catList);

      // Viewer engine groupings
      if (fmt.viewerEngine && fmt.hasViewer) {
        const viewList = this.viewerFormats.get(fmt.viewerEngine) || [];
        viewList.push(fmt);
        this.viewerFormats.set(fmt.viewerEngine, viewList);
      }

      // Editor capability groupings
      if (fmt.editorCapability && fmt.editorCapability !== 'none') {
        const cap = fmt.editorCapability;
        const editList = this.editorFormats.get(cap) || [];
        editList.push(fmt);
        this.editorFormats.set(cap, editList);
      }
    }
  }

  /** Get format by extension */
  get(ext: string): FormatDefinition | undefined {
    return this.formatMap.get(ext.toLowerCase());
  }

  /** Check if format exists */
  has(ext: string): boolean {
    return this.formatMap.has(ext.toLowerCase());
  }

  /** Get all formats */
  getAll(): FormatDefinition[] {
    return [...FORMAT_DEFINITIONS];
  }

  /** Get formats by category */
  getByCategory(category: FormatCategory): FormatDefinition[] {
    return this.categoryFormats.get(category) || [];
  }

  /** Get formats by tier */
  getByTier(tier: FormatTier): FormatDefinition[] {
    return FORMAT_DEFINITIONS.filter(f => f.tier === tier);
  }

  /** Get category definition */
  getCategory(category: FormatCategory): CategoryDefinition {
    return CATEGORY_DEFINITIONS[category];
  }

  /** Get all categories */
  getAllCategories(): FormatCategory[] {
    return Object.keys(CATEGORY_DEFINITIONS) as FormatCategory[];
  }

  /** Get display name */
  getDisplayName(ext: string): string {
    return this.get(ext)?.name ?? ext.toUpperCase();
  }

  /** Get MIME type */
  getMime(ext: string): string {
    return this.get(ext)?.mime ?? 'application/octet-stream';
  }

  /** Search formats */
  search(query: string): FormatDefinition[] {
    const q = query.toLowerCase();
    return FORMAT_DEFINITIONS.filter(f =>
      f.ext.includes(q) ||
      f.name.toLowerCase().includes(q) ||
      f.description?.toLowerCase().includes(q)
    );
  }

  /** Get formats by viewer engine */
  getByViewerEngine(engine: string): FormatDefinition[] {
    return this.viewerFormats.get(engine) || [];
  }

  /** Get formats with viewer support */
  getViewableFormats(): FormatDefinition[] {
    return FORMAT_DEFINITIONS.filter(f => f.hasViewer);
  }

  /** Get formats by editor capability */
  getByEditorCapability(capability: string): FormatDefinition[] {
    return this.editorFormats.get(capability) || [];
  }

  /** Get editable formats */
  getEditableFormats(): FormatDefinition[] {
    return FORMAT_DEFINITIONS.filter(f => f.editorCapability && f.editorCapability !== 'none');
  }

  /** Get formats by provider type */
  getByProvider(providerType: keyof import('../types/formats').FormatProviderCapabilities): FormatDefinition[] {
    return FORMAT_DEFINITIONS.filter(f => f.providers?.[providerType]);
  }

  /** Get formats supporting batch */
  getBatchSupported(): FormatDefinition[] {
    return FORMAT_DEFINITIONS.filter(f => f.supportsBatch);
  }

  /** Get popular formats (high search priority) */
  getPopular(limit = 20): FormatDefinition[] {
    return [...FORMAT_DEFINITIONS]
      .filter(f => f.searchPriority && f.searchPriority >= 70)
      .sort((a, b) => (b.searchPriority ?? 0) - (a.searchPriority ?? 0))
      .slice(0, limit);
  }

  /** Get formats by search volume */
  getBySearchVolume(minVolume: number): FormatDefinition[] {
    return FORMAT_DEFINITIONS
      .filter(f => f.searchVolume && f.searchVolume >= minVolume)
      .sort((a, b) => (b.searchVolume ?? 0) - (a.searchVolume ?? 0));
  }

  /** Get random formats for SEO pages */
  getRandom(limit = 10): FormatDefinition[] {
    const shuffled = [...FORMAT_DEFINITIONS].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, limit);
  }

  /** Check if format is viewable */
  isViewable(ext: string): boolean {
    return this.get(ext)?.hasViewer ?? false;
  }

  /** Check if format is editable */
  isEditable(ext: string): boolean {
    const fmt = this.get(ext);
    return fmt?.editorCapability !== undefined && fmt.editorCapability !== 'none';
  }

  /** Get converter route for format */
  getConverterRoute(ext: string): string | null {
    const fmt = this.get(ext);
    if (!fmt) return null;
    const category = CATEGORY_DEFINITIONS[fmt.category];
    return category.converterRoute ?? null;
  }

  /** Get all extensions */
  getAllExtensions(): string[] {
    return FORMAT_DEFINITIONS.map(f => f.ext);
  }

  /** Get extensions by category */
  getExtensionsByCategory(category: FormatCategory): string[] {
    return this.getByCategory(category).map(f => f.ext);
  }

  /** Infer category from extension */
  inferCategory(ext: string): FormatCategory | null {
    return this.get(ext)?.category ?? null;
  }
}

export const formatRegistry = new FormatRegistry();
