/**
 * lib/registry/library-registry.ts
 *
 * Universal Library Registry — Phase 6A
 * Single source of truth for every processing library the platform supports,
 * plans to support, or uses as a fallback.  No library code is imported here;
 * this is purely metadata.
 */

// ---------------------------------------------------------------------------
// TYPES
// ---------------------------------------------------------------------------

export type LibraryStatus =
  | "primary"       // Active default for this domain
  | "secondary"     // Active alternative
  | "fallback"      // Used only when primary/secondary unavailable
  | "premium"       // Available on paid tiers only
  | "future"        // Planned but not integrated yet
  | "experimental"; // Under evaluation / unstable

export type LibraryTier =
  | "browser"   // Runs entirely in browser (WASM / JS)
  | "server"    // Server-side only (Node.js / native binary)
  | "cloud"     // Third-party cloud API
  | "hybrid";   // Both browser and server

export type LibrarySupportedDomain =
  | "image" | "vector" | "raw" | "icon" | "3d" | "cad"
  | "video" | "audio"
  | "pdf" | "document" | "spreadsheet" | "presentation" | "ebook"
  | "archive" | "font" | "gis" | "email"
  | "code" | "webpage" | "subtitle" | "certificate"
  | "scientific" | "medical" | "disk-image" | "executable"
  | "ocr";

export interface LibraryDefinition {
  /** Unique registry identifier */
  id: string;
  /** Human-readable name */
  name: string;
  /** npm / pip / system package name */
  package: string;
  /** Official homepage or repository */
  homepage: string;
  /** SPDX license identifier */
  license: string;
  /** Whether it can run in a browser (via WASM, pure JS, etc.) */
  browserSupport: boolean;
  /** Whether a server runtime (Node, native binary) is required */
  serverRequired: boolean;
  /** Processing domains this library handles */
  supportedDomains: LibrarySupportedDomain[];
  /** Processor IDs that can use this library */
  supportedProcessors: string[];
  /** Provider IDs that are implemented on top of this library */
  supportedProviders: string[];
  /** Hosting tier */
  tier: LibraryTier;
  /** Relative priority when multiple libraries can handle the same task (lower = preferred) */
  priority: number;
  /** Integration status */
  status: LibraryStatus;
  /** Approximate uncompressed JS/WASM bundle size (bytes). 0 = server-only, unknown */
  bundleSize?: number;
  /** Input format extensions this library can read */
  inputFormats: string[];
  /** Output format extensions this library can produce */
  outputFormats: string[];
  /** True if concurrent / parallel processing is supported */
  supportsParallel: boolean;
  /** True if streaming / incremental output is possible */
  supportsStreaming: boolean;
  /** Estimated max file size this library handles reliably (bytes). 0 = unlimited/unknown */
  maxFileSizeBytes: number;
  /** Short one-line description */
  description: string;
}

// ---------------------------------------------------------------------------
// LIBRARY DEFINITIONS
// ---------------------------------------------------------------------------

export const LIBRARY_DEFINITIONS: LibraryDefinition[] = [

  // ── IMAGE ──────────────────────────────────────────────────────────────────

  {
    id: "canvas-api",
    name: "Canvas API",
    package: "(browser built-in)",
    homepage: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
    license: "W3C",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["image", "icon"],
    supportedProcessors: ["image-converter", "image-resizer", "image-compressor", "image-cropper"],
    supportedProviders: ["CanvasImageProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 0,
    inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp", "ico", "svg", "avif", "tif", "tiff"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "bmp"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Native browser 2D raster rendering — zero bundle cost",
  },
  {
    id: "sharp",
    name: "Sharp",
    package: "sharp",
    homepage: "https://sharp.pixelplumbing.com",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["image", "raw"],
    supportedProcessors: ["image-converter", "image-resizer", "image-compressor", "image-optimizer"],
    supportedProviders: ["SharpImageProvider"],
    tier: "server",
    priority: 1,
    status: "primary",
    inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "tiff", "avif", "heic", "heif", "raw"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "gif", "tiff", "avif", "heic"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "High-performance Node.js image processing (libvips-backed)",
  },
  {
    id: "imagemagick",
    name: "ImageMagick",
    package: "imagemagick (system)",
    homepage: "https://imagemagick.org",
    license: "ImageMagick",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["image", "vector", "raw", "icon"],
    supportedProcessors: ["image-converter", "image-editor", "image-resizer"],
    supportedProviders: ["ImageMagickProvider"],
    tier: "server",
    priority: 2,
    status: "secondary",
    inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp", "tiff", "avif", "heic", "svg", "eps", "ai", "psd", "ico"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp", "tiff", "avif", "ico", "svg"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Battle-tested server-side image manipulation suite",
  },
  {
    id: "libvips",
    name: "libvips",
    package: "libvips (system)",
    homepage: "https://libvips.github.io",
    license: "LGPL-2.1",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["image", "raw"],
    supportedProcessors: ["image-converter", "image-resizer"],
    supportedProviders: ["LibvipsProvider"],
    tier: "server",
    priority: 1,
    status: "primary",
    inputFormats: ["png", "jpg", "jpeg", "webp", "tiff", "heic", "avif", "svg"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "tiff", "avif"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 4 * 1024 * 1024 * 1024,
    description: "Fastest low-memory server-side image processing",
  },
  {
    id: "squoosh",
    name: "Squoosh (libsquoosh)",
    package: "@squoosh/lib",
    homepage: "https://github.com/GoogleChromeLabs/squoosh",
    license: "Apache-2.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["image"],
    supportedProcessors: ["image-compressor", "image-converter"],
    supportedProviders: ["SquooshImageProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 1.5 * 1024 * 1024,
    inputFormats: ["png", "jpg", "jpeg", "webp", "avif"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "avif", "jxl"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 20 * 1024 * 1024,
    description: "Google's browser-based image compression library",
  },
  {
    id: "pica",
    name: "Pica",
    package: "pica",
    homepage: "https://github.com/nodeca/pica",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["image"],
    supportedProcessors: ["image-resizer"],
    supportedProviders: ["PicaResizeProvider"],
    tier: "browser",
    priority: 3,
    status: "secondary",
    bundleSize: 150 * 1024,
    inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp"],
    outputFormats: ["png", "jpg", "jpeg", "webp"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "High-quality browser image resizing with Web Workers",
  },
  {
    id: "jimp",
    name: "Jimp",
    package: "jimp",
    homepage: "https://github.com/jimp-dev/jimp",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["image"],
    supportedProcessors: ["image-converter", "image-editor"],
    supportedProviders: ["JimpImageProvider"],
    tier: "hybrid",
    priority: 3,
    status: "fallback",
    bundleSize: 800 * 1024,
    inputFormats: ["png", "jpg", "jpeg", "bmp", "gif", "tiff"],
    outputFormats: ["png", "jpg", "jpeg", "bmp", "gif", "tiff"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 30 * 1024 * 1024,
    description: "Pure JS image processing — works everywhere, not the fastest",
  },
  {
    id: "cloudinary",
    name: "Cloudinary SDK",
    package: "cloudinary",
    homepage: "https://cloudinary.com",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["image", "video"],
    supportedProcessors: ["image-converter", "image-resizer", "image-compressor", "video-converter"],
    supportedProviders: ["CloudinaryProvider"],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["png", "jpg", "jpeg", "webp", "gif", "bmp", "tiff", "avif", "svg", "mp4", "webm"],
    outputFormats: ["png", "jpg", "jpeg", "webp", "gif", "avif", "mp4", "webm"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Full-featured cloud image & video transformation API",
  },

  // ── VIDEO ──────────────────────────────────────────────────────────────────

  {
    id: "ffmpeg-wasm",
    name: "FFmpeg.wasm",
    package: "@ffmpeg/ffmpeg",
    homepage: "https://ffmpegwasm.netlify.app",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["video", "audio", "image"],
    supportedProcessors: ["video-converter", "audio-converter", "gif-converter"],
    supportedProviders: ["FFmpegWasmProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 31 * 1024 * 1024,
    inputFormats: ["mp4", "webm", "avi", "mov", "mkv", "wmv", "flv", "mpeg", "mpg", "m4v", "3gp", "ogv", "ts", "mp3", "wav", "ogg", "flac", "aac", "m4a"],
    outputFormats: ["mp4", "webm", "avi", "mov", "mkv", "ogv", "mp3", "wav", "ogg", "flac", "aac", "m4a", "gif"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "FFmpeg compiled to WebAssembly — server-grade AV in the browser",
  },
  {
    id: "ffmpeg-mt",
    name: "FFmpeg.wasm (multi-thread)",
    package: "@ffmpeg/ffmpeg",
    homepage: "https://ffmpegwasm.netlify.app",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["video", "audio"],
    supportedProcessors: ["video-converter", "audio-converter"],
    supportedProviders: ["FFmpegMTProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 31 * 1024 * 1024,
    inputFormats: ["mp4", "webm", "avi", "mov", "mkv"],
    outputFormats: ["mp4", "webm", "avi", "mov", "mkv"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Multi-threaded FFmpeg.wasm — SharedArrayBuffer required",
  },
  {
    id: "webcodecs",
    name: "WebCodecs API",
    package: "(browser built-in)",
    homepage: "https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API",
    license: "W3C",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["video", "audio"],
    supportedProcessors: ["video-converter"],
    supportedProviders: ["WebCodecsProvider"],
    tier: "browser",
    priority: 1,
    status: "experimental",
    bundleSize: 0,
    inputFormats: ["mp4", "webm"],
    outputFormats: ["mp4", "webm"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 0,
    description: "Low-level browser codec API — high performance, Chrome 94+",
  },
  {
    id: "ffmpeg-server",
    name: "FFmpeg (Server)",
    package: "ffmpeg (system)",
    homepage: "https://ffmpeg.org",
    license: "LGPL-2.1",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["video", "audio", "image"],
    supportedProcessors: ["video-converter", "audio-converter", "gif-converter"],
    supportedProviders: ["FFmpegServerProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["mp4", "webm", "avi", "mov", "mkv", "wmv", "flv", "mpeg", "mpg", "m4v", "3gp", "hevc", "m2ts", "rm", "rmvb", "mp3", "wav", "ogg", "flac", "aac", "m4a", "alac", "wma"],
    outputFormats: ["mp4", "webm", "avi", "mov", "mkv", "wmv", "ogv", "mp3", "wav", "ogg", "flac", "aac", "m4a", "gif"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 0,
    description: "Native FFmpeg server binary — full codec support, requires Docker",
  },
  {
    id: "gpu-ffmpeg",
    name: "FFmpeg GPU-Accelerated",
    package: "ffmpeg (system, with NVENC/VAAPI)",
    homepage: "https://ffmpeg.org",
    license: "LGPL-2.1",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["video"],
    supportedProcessors: ["video-converter"],
    supportedProviders: ["GPUFFmpegProvider"],
    tier: "server",
    priority: 1,
    status: "future",
    inputFormats: ["mp4", "mkv", "avi"],
    outputFormats: ["mp4", "mkv", "webm"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 0,
    description: "GPU-accelerated FFmpeg transcoding (NVENC / VAAPI). Planned.",
  },

  // ── AUDIO ──────────────────────────────────────────────────────────────────

  {
    id: "web-audio-api",
    name: "Web Audio API",
    package: "(browser built-in)",
    homepage: "https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API",
    license: "W3C",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["audio"],
    supportedProcessors: ["audio-converter", "audio-editor"],
    supportedProviders: ["WebAudioProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 0,
    inputFormats: ["mp3", "wav", "ogg", "flac", "aac", "m4a"],
    outputFormats: ["wav"],
    supportsParallel: false,
    supportsStreaming: true,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "Native browser audio decode/encode (limited output formats)",
  },
  {
    id: "tone-js",
    name: "Tone.js",
    package: "tone",
    homepage: "https://tonejs.github.io",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["audio"],
    supportedProcessors: ["audio-editor"],
    supportedProviders: ["ToneProvider"],
    tier: "browser",
    priority: 3,
    status: "secondary",
    bundleSize: 600 * 1024,
    inputFormats: ["mp3", "wav", "ogg"],
    outputFormats: ["wav"],
    supportsParallel: false,
    supportsStreaming: true,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Web Audio framework for music and synthesis",
  },

  // ── PDF ────────────────────────────────────────────────────────────────────

  {
    id: "pdf-lib",
    name: "pdf-lib",
    package: "pdf-lib",
    homepage: "https://pdf-lib.js.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["pdf", "document"],
    supportedProcessors: ["pdf-converter", "pdf-editor", "pdf-merger", "pdf-splitter"],
    supportedProviders: ["PDFLibProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 800 * 1024,
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "Pure JS PDF creation & modification — works in browser and Node.js",
  },
  {
    id: "pdfjs",
    name: "PDF.js",
    package: "pdfjs-dist",
    homepage: "https://mozilla.github.io/pdf.js",
    license: "Apache-2.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["pdf"],
    supportedProcessors: ["pdf-viewer", "pdf-converter"],
    supportedProviders: ["PDFJSProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 2 * 1024 * 1024,
    inputFormats: ["pdf"],
    outputFormats: ["png", "jpg", "canvas"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Mozilla PDF rendering engine — renders PDFs to canvas",
  },
  {
    id: "pdfium",
    name: "PDFium",
    package: "pdfium-lib (system)",
    homepage: "https://pdfium.googlesource.com/pdfium",
    license: "BSD-3-Clause",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["pdf"],
    supportedProcessors: ["pdf-converter", "pdf-renderer"],
    supportedProviders: ["PDFiumProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["pdf"],
    outputFormats: ["png", "jpg", "svg", "txt"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Google's PDF engine — used in Chrome, best fidelity",
  },
  {
    id: "mupdf",
    name: "MuPDF",
    package: "mupdf (system)",
    homepage: "https://mupdf.com",
    license: "AGPL-3.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["pdf", "ebook"],
    supportedProcessors: ["pdf-converter", "ebook-viewer"],
    supportedProviders: ["MuPDFProvider"],
    tier: "hybrid",
    priority: 2,
    status: "secondary",
    bundleSize: 15 * 1024 * 1024,
    inputFormats: ["pdf", "xps", "epub", "cbz"],
    outputFormats: ["pdf", "png", "svg", "txt"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
    description: "Lightweight WASM-capable PDF/XPS/EPUB renderer",
  },
  {
    id: "ghostscript",
    name: "Ghostscript",
    package: "ghostscript (system)",
    homepage: "https://ghostscript.com",
    license: "AGPL-3.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["pdf", "vector"],
    supportedProcessors: ["pdf-converter", "pdf-compressor"],
    supportedProviders: ["GhostscriptProvider"],
    tier: "server",
    priority: 2,
    status: "premium",
    inputFormats: ["pdf", "eps", "ps"],
    outputFormats: ["pdf", "png", "jpg", "svg", "eps"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Postscript / PDF interpretation — excellent compression control",
  },

  // ── DOCUMENTS ─────────────────────────────────────────────────────────────

  {
    id: "mammoth",
    name: "Mammoth.js",
    package: "mammoth",
    homepage: "https://github.com/mwilliamson/mammoth.js",
    license: "BSD-2-Clause",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["document"],
    supportedProcessors: ["document-converter"],
    supportedProviders: ["MammothProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 400 * 1024,
    inputFormats: ["docx"],
    outputFormats: ["html", "txt", "md"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Word DOCX to HTML converter — preserves semantic structure",
  },
  {
    id: "docx-preview",
    name: "docx-preview",
    package: "docx-preview",
    homepage: "https://github.com/VolodymyrBaydalka/docxjs",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["document"],
    supportedProcessors: ["document-viewer"],
    supportedProviders: ["DocxPreviewProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 900 * 1024,
    inputFormats: ["docx"],
    outputFormats: ["html"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "DOCX viewer — high-fidelity rendering with style support",
  },
  {
    id: "libreoffice",
    name: "LibreOffice",
    package: "libreoffice (system)",
    homepage: "https://www.libreoffice.org",
    license: "MPL-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["document", "spreadsheet", "presentation", "pdf"],
    supportedProcessors: ["document-converter", "spreadsheet-converter", "presentation-converter"],
    supportedProviders: ["LibreOfficeProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["docx", "doc", "odt", "xlsx", "xls", "ods", "pptx", "ppt", "odp", "txt", "rtf", "html", "csv"],
    outputFormats: ["pdf", "docx", "odt", "xlsx", "ods", "pptx", "odp", "txt", "html", "csv", "png", "jpg"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Full office suite for server-side document conversion",
  },
  {
    id: "aspose-words",
    name: "Aspose Words",
    package: "aspose-words (cloud API)",
    homepage: "https://products.aspose.com/words",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["document", "pdf"],
    supportedProcessors: ["document-converter"],
    supportedProviders: ["AsposeWordsProvider"],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["docx", "doc", "odt", "rtf", "txt", "html", "md"],
    outputFormats: ["docx", "pdf", "odt", "html", "md", "txt", "epub"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Commercial cloud document conversion API with high fidelity",
  },

  // ── SPREADSHEET ───────────────────────────────────────────────────────────

  {
    id: "sheetjs",
    name: "SheetJS (xlsx)",
    package: "xlsx",
    homepage: "https://sheetjs.com",
    license: "Apache-2.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["spreadsheet"],
    supportedProcessors: ["spreadsheet-converter", "csv-converter"],
    supportedProviders: ["SheetJSProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 900 * 1024,
    inputFormats: ["xlsx", "xls", "xlsm", "xlsb", "ods", "csv", "tsv", "numbers"],
    outputFormats: ["xlsx", "xls", "ods", "csv", "tsv", "html", "json"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Industry-standard browser spreadsheet read/write library",
  },
  {
    id: "exceljs",
    name: "ExcelJS",
    package: "exceljs",
    homepage: "https://github.com/exceljs/exceljs",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["spreadsheet"],
    supportedProcessors: ["spreadsheet-converter"],
    supportedProviders: ["ExcelJSProvider"],
    tier: "hybrid",
    priority: 2,
    status: "secondary",
    bundleSize: 1.2 * 1024 * 1024,
    inputFormats: ["xlsx", "xls", "csv"],
    outputFormats: ["xlsx", "csv", "html"],
    supportsParallel: false,
    supportsStreaming: true,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "Streaming Excel read/write with rich formatting support",
  },
  {
    id: "aspose-cells",
    name: "Aspose Cells",
    package: "aspose-cells (cloud API)",
    homepage: "https://products.aspose.com/cells",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["spreadsheet"],
    supportedProcessors: ["spreadsheet-converter"],
    supportedProviders: ["AsposeCellsProvider"],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["xlsx", "xls", "xlsm", "xlsb", "ods", "csv", "numbers"],
    outputFormats: ["xlsx", "pdf", "html", "csv", "json", "png", "jpg"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Commercial cloud spreadsheet conversion API",
  },

  // ── PRESENTATION ──────────────────────────────────────────────────────────

  {
    id: "pptxgenjs",
    name: "PptxGenJS",
    package: "pptxgenjs",
    homepage: "https://gitbrent.github.io/PptxGenJS",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["presentation"],
    supportedProcessors: ["presentation-converter"],
    supportedProviders: ["PptxGenProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 400 * 1024,
    inputFormats: [],
    outputFormats: ["pptx"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Create PowerPoint presentations programmatically in browser",
  },
  {
    id: "aspose-slides",
    name: "Aspose Slides",
    package: "aspose-slides (cloud API)",
    homepage: "https://products.aspose.com/slides",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["presentation"],
    supportedProcessors: ["presentation-converter"],
    supportedProviders: ["AsposeSlidesProvider"],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["pptx", "ppt", "odp", "key"],
    outputFormats: ["pptx", "pdf", "png", "jpg", "html"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Commercial cloud presentation conversion API",
  },

  // ── OCR ────────────────────────────────────────────────────────────────────

  {
    id: "tesseract-js",
    name: "Tesseract.js",
    package: "tesseract.js",
    homepage: "https://tesseract.projectnaptha.com",
    license: "Apache-2.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["ocr", "image", "pdf"],
    supportedProcessors: ["ocr-processor"],
    supportedProviders: ["TesseractProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 30 * 1024 * 1024,
    inputFormats: ["png", "jpg", "jpeg", "webp", "bmp", "tiff", "pdf"],
    outputFormats: ["txt", "pdf", "html", "json"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Google Tesseract OCR compiled to WASM — 100+ languages",
  },
  {
    id: "paddleocr",
    name: "PaddleOCR",
    package: "paddlepaddle-gpu (Python)",
    homepage: "https://github.com/PaddlePaddle/PaddleOCR",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["ocr"],
    supportedProcessors: ["ocr-processor"],
    supportedProviders: ["PaddleOCRProvider"],
    tier: "server",
    priority: 2,
    status: "premium",
    inputFormats: ["png", "jpg", "jpeg", "bmp", "tiff"],
    outputFormats: ["txt", "json", "pdf"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Baidu's high-accuracy OCR — outperforms Tesseract on complex layouts",
  },
  {
    id: "google-vision",
    name: "Google Cloud Vision",
    package: "@google-cloud/vision",
    homepage: "https://cloud.google.com/vision",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["ocr", "image"],
    supportedProcessors: ["ocr-processor"],
    supportedProviders: ["GoogleVisionProvider"],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["png", "jpg", "jpeg", "gif", "webp", "bmp", "tiff", "pdf"],
    outputFormats: ["txt", "json", "pdf"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 20 * 1024 * 1024,
    description: "Google Vision API — state-of-the-art cloud OCR",
  },
  {
    id: "azure-ocr",
    name: "Azure Computer Vision",
    package: "@azure/cognitiveservices-computervision",
    homepage: "https://azure.microsoft.com/en-us/products/cognitive-services/computer-vision",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["ocr"],
    supportedProcessors: ["ocr-processor"],
    supportedProviders: ["AzureOCRProvider"],
    tier: "cloud",
    priority: 2,
    status: "premium",
    inputFormats: ["png", "jpg", "jpeg", "bmp", "tiff", "pdf"],
    outputFormats: ["txt", "json"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Microsoft Azure Read API — enterprise OCR",
  },
  {
    id: "mistral-ocr",
    name: "Mistral OCR",
    package: "@mistralai/mistralai",
    homepage: "https://mistral.ai",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["ocr", "document"],
    supportedProcessors: ["ocr-processor"],
    supportedProviders: ["MistralOCRProvider"],
    tier: "cloud",
    priority: 1,
    status: "future",
    inputFormats: ["pdf", "png", "jpg"],
    outputFormats: ["txt", "md", "json"],
    supportsParallel: true,
    supportsStreaming: true,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Mistral vision-based document understanding — planned",
  },

  // ── ARCHIVE ────────────────────────────────────────────────────────────────

  {
    id: "jszip",
    name: "JSZip",
    package: "jszip",
    homepage: "https://stuk.github.io/jszip",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["archive"],
    supportedProcessors: ["archive-extractor", "archive-creator"],
    supportedProviders: ["JSZipProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 120 * 1024,
    inputFormats: ["zip"],
    outputFormats: ["zip"],
    supportsParallel: false,
    supportsStreaming: true,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Read and write ZIP archives in browser and Node.js",
  },
  {
    id: "node-unrar-js",
    name: "node-unrar-js",
    package: "node-unrar-js",
    homepage: "https://github.com/YuJianrong/node-unrar-js",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["archive"],
    supportedProcessors: ["archive-extractor"],
    supportedProviders: ["UnrarProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 500 * 1024,
    inputFormats: ["rar"],
    outputFormats: [],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "Unrar library compiled to WASM — extract RAR archives in browser",
  },
  {
    id: "7zip-wasm",
    name: "7zip-wasm",
    // npm package: 7z-wasm@1.2.0 (installed)
    // Note: the npm package name is "7z-wasm"; this library registry entry retains
    // "7zip-wasm" as the canonical libraryId used across all registries.
    package: "7z-wasm",
    homepage: "https://www.npmjs.com/package/7z-wasm",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["archive"],
    supportedProcessors: ["archive-extractor", "archive-creator"],
    supportedProviders: ["SevenZipProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 6 * 1024 * 1024,
    // Formats per archive-capability.ts. RAR is extract-only via 7-Zip.
    inputFormats: ["7z", "tar", "gz", "bz2", "xz", "cab", "zip", "rar"],
    outputFormats: ["7z", "tar", "gz", "bz2", "xz", "zip"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
    description: "7-Zip compiled to WASM (7z-wasm) — infrastructure registered. Factory loader activates Phase 6C SevenZipEngine.",
  },
  {
    id: "libarchive",
    name: "libarchive.js",
    package: "libarchive.js",
    homepage: "https://github.com/nika-begiashvili/libarchivejs",
    license: "BSD-2-Clause",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["archive"],
    supportedProcessors: ["archive-extractor"],
    supportedProviders: ["LibarchiveProvider"],
    tier: "browser",
    priority: 3,
    status: "fallback",
    bundleSize: 4 * 1024 * 1024,
    inputFormats: ["tar", "gz", "bz2", "xz", "7z", "zip", "cpio"],
    outputFormats: [],
    supportsParallel: false,
    supportsStreaming: true,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "libarchive compiled to WASM — comprehensive archive extraction",
  },

  // ── WEBPAGE ────────────────────────────────────────────────────────────────

  {
    id: "puppeteer",
    name: "Puppeteer",
    package: "puppeteer",
    homepage: "https://pptr.dev",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["webpage", "pdf"],
    supportedProcessors: ["webpage-to-pdf", "webpage-to-image", "webpage-to-screenshot"],
    supportedProviders: ["PuppeteerProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["html", "url", "xhtml", "mhtml"],
    outputFormats: ["pdf", "png", "jpg", "webp"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 0,
    description: "Headless Chrome — renders any webpage to PDF or image",
  },
  {
    id: "playwright",
    name: "Playwright",
    package: "playwright",
    homepage: "https://playwright.dev",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["webpage"],
    supportedProcessors: ["webpage-to-pdf", "webpage-to-image"],
    supportedProviders: ["PlaywrightProvider"],
    tier: "server",
    priority: 2,
    status: "premium",
    inputFormats: ["html", "url"],
    outputFormats: ["pdf", "png", "jpg"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 0,
    description: "Cross-browser automation — Chrome, Firefox, WebKit",
  },
  {
    id: "html2canvas",
    name: "html2canvas",
    package: "html2canvas",
    homepage: "https://html2canvas.hertzen.com",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["webpage"],
    supportedProcessors: ["webpage-to-image"],
    supportedProviders: ["Html2CanvasProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 500 * 1024,
    inputFormats: ["html"],
    outputFormats: ["png", "jpg"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Render HTML to canvas element — client-side screenshot",
  },
  {
    id: "dom-to-image",
    name: "dom-to-image-more",
    package: "dom-to-image-more",
    homepage: "https://github.com/1904labs/dom-to-image-more",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["webpage"],
    supportedProcessors: ["webpage-to-image"],
    supportedProviders: ["DomToImageProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 200 * 1024,
    inputFormats: ["html"],
    outputFormats: ["png", "jpg", "svg"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 20 * 1024 * 1024,
    description: "DOM snapshot to PNG/SVG — alternative to html2canvas",
  },
  {
    id: "wkhtmltopdf",
    name: "wkhtmltopdf",
    package: "wkhtmltopdf (system)",
    homepage: "https://wkhtmltopdf.org",
    license: "LGPL-3.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["webpage", "pdf"],
    supportedProcessors: ["webpage-to-pdf"],
    supportedProviders: ["WkhtmltopdfProvider"],
    tier: "server",
    priority: 3,
    status: "fallback",
    inputFormats: ["html", "url"],
    outputFormats: ["pdf", "jpg", "png"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "HTML to PDF using WebKit — legacy but dependency-free",
  },

  // ── VECTOR ────────────────────────────────────────────────────────────────

  {
    id: "svgo",
    name: "SVGO",
    package: "svgo",
    homepage: "https://svgo.dev",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["vector"],
    supportedProcessors: ["svg-optimizer", "svg-converter"],
    supportedProviders: ["SVGOProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 450 * 1024,
    inputFormats: ["svg"],
    outputFormats: ["svg"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "SVG optimiser — removes redundant markup, shrinks file size",
  },
  {
    id: "svgson",
    name: "svgson",
    package: "svgson",
    homepage: "https://github.com/elrumordelaluz/svgson",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["vector"],
    supportedProcessors: ["svg-converter"],
    supportedProviders: ["SvgsonProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 50 * 1024,
    inputFormats: ["svg"],
    outputFormats: ["json"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "SVG → JSON / JSON → SVG transform utility",
  },
  {
    id: "inkscape",
    name: "Inkscape (CLI)",
    package: "inkscape (system)",
    homepage: "https://inkscape.org",
    license: "GPL-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["vector"],
    supportedProcessors: ["vector-converter", "svg-converter"],
    supportedProviders: ["InkscapeProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["svg", "ai", "eps", "wmf", "emf", "cdr"],
    outputFormats: ["png", "pdf", "svg", "eps"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Full vector editor CLI — excellent SVG/PDF export quality",
  },

  // ── FONTS ──────────────────────────────────────────────────────────────────

  {
    id: "opentype-js",
    name: "OpenType.js",
    package: "opentype.js",
    homepage: "https://opentype.js.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["font"],
    supportedProcessors: ["font-converter", "font-renderer"],
    supportedProviders: ["OpenTypeProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 300 * 1024,
    inputFormats: ["ttf", "otf", "woff"],
    outputFormats: ["svg", "ttf", "otf"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "Read and write OpenType fonts — glyph rendering, subsetting",
  },
  {
    id: "fontkit",
    name: "Fontkit",
    package: "@pdf-lib/fontkit",
    homepage: "https://github.com/foliojs/fontkit",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["font"],
    supportedProcessors: ["font-converter"],
    supportedProviders: ["FontkitProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 500 * 1024,
    inputFormats: ["ttf", "otf", "woff", "woff2", "ttc", "dfont"],
    outputFormats: ["ttf", "otf"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "Advanced font subsetting and shaping — used by pdf-lib",
  },

  // ── 3D ─────────────────────────────────────────────────────────────────────

  {
    id: "three-js",
    name: "Three.js",
    package: "three",
    homepage: "https://threejs.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["3d"],
    supportedProcessors: ["3d-viewer", "3d-converter"],
    supportedProviders: ["ThreeJSProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 600 * 1024,
    inputFormats: ["glb", "gltf", "obj", "fbx", "stl", "dae", "ply"],
    outputFormats: ["glb", "gltf", "obj"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "3D WebGL rendering library — loaders for most 3D formats",
  },
  {
    id: "babylon-js",
    name: "Babylon.js",
    package: "@babylonjs/core",
    homepage: "https://www.babylonjs.com",
    license: "Apache-2.0",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["3d"],
    supportedProcessors: ["3d-viewer"],
    supportedProviders: ["BabylonJSProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 2 * 1024 * 1024,
    inputFormats: ["glb", "gltf", "fbx", "obj", "stl"],
    outputFormats: ["glb"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Full-featured WebGPU/WebGL engine — alternative to Three.js",
  },
  {
    id: "assimp-js",
    name: "AssimpJS",
    package: "assimpjs",
    homepage: "https://github.com/kovacsv/assimpjs",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["3d"],
    supportedProcessors: ["3d-converter"],
    supportedProviders: ["AssimpProvider"],
    tier: "browser",
    priority: 1,
    status: "secondary",
    bundleSize: 8 * 1024 * 1024,
    inputFormats: ["fbx", "obj", "stl", "dae", "ply", "3ds", "blend", "lwo"],
    outputFormats: ["obj", "stl", "glb", "gltf", "dae"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Open Asset Import Library compiled to WASM — 40+ 3D formats",
  },
  {
    id: "opencascade",
    name: "OpenCascade.js",
    package: "opencascade.js",
    homepage: "https://ocjs.org",
    license: "LGPL-2.1",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["cad", "3d"],
    supportedProcessors: ["cad-converter"],
    supportedProviders: ["OpenCascadeProvider"],
    tier: "browser",
    priority: 1,
    status: "experimental",
    bundleSize: 20 * 1024 * 1024,
    inputFormats: ["step", "iges", "brep"],
    outputFormats: ["step", "stl", "obj", "glb"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "OpenCASCADE CAD kernel in WASM — exact STEP/IGES geometry",
  },

  // ── GIS ─────────────────────────────────────────────────────────────────────

  {
    id: "turf-js",
    name: "Turf.js",
    package: "@turf/turf",
    homepage: "https://turfjs.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["gis"],
    supportedProcessors: ["gis-converter", "gis-calculator"],
    supportedProviders: ["TurfProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 700 * 1024,
    inputFormats: ["geojson", "topojson"],
    outputFormats: ["geojson"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Geospatial analysis and transformation in JavaScript",
  },
  {
    id: "gdal",
    name: "GDAL/OGR",
    package: "gdal-async (Node) / gdal.js (WASM)",
    homepage: "https://gdal.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["gis"],
    supportedProcessors: ["gis-converter"],
    supportedProviders: ["GDALProvider"],
    tier: "hybrid",
    priority: 1,
    status: "secondary",
    bundleSize: 40 * 1024 * 1024,
    inputFormats: ["shp", "geojson", "kml", "kmz", "gpkg", "gpx", "geotiff"],
    outputFormats: ["geojson", "kml", "shp", "gpkg", "csv"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Universal geospatial format conversion — compiled to WASM",
  },
  {
    id: "maplibre",
    name: "MapLibre GL JS",
    package: "maplibre-gl",
    homepage: "https://maplibre.org",
    license: "BSD-2-Clause",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["gis"],
    supportedProcessors: ["gis-viewer"],
    supportedProviders: ["MapLibreProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 2 * 1024 * 1024,
    inputFormats: ["geojson", "topojson", "kml"],
    outputFormats: ["png"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 0,
    description: "Open-source MapboxGL fork — vector tile map renderer",
  },

  // ── MEDICAL ────────────────────────────────────────────────────────────────

  {
    id: "dcmjs",
    name: "dcmjs",
    package: "dcmjs",
    homepage: "https://github.com/dcmjs-org/dcmjs",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["medical"],
    supportedProcessors: ["medical-viewer", "dicom-converter"],
    supportedProviders: ["DCMJSProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 1.5 * 1024 * 1024,
    inputFormats: ["dcm", "dicom"],
    outputFormats: ["png", "jpg", "json"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "DICOM standard JS implementation — parse and render medical images",
  },
  {
    id: "ohif",
    name: "OHIF Viewers",
    package: "@ohif/core",
    homepage: "https://ohif.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["medical"],
    supportedProcessors: ["medical-viewer"],
    supportedProviders: ["OHIFProvider"],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 5 * 1024 * 1024,
    inputFormats: ["dcm", "dicom", "nii"],
    outputFormats: ["png", "jpg"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 1 * 1024 * 1024 * 1024,
    description: "Open Health Imaging Foundation — full DICOM viewer stack",
  },

  // ── CERTIFICATES ──────────────────────────────────────────────────────────

  {
    id: "node-forge",
    name: "node-forge",
    package: "node-forge",
    homepage: "https://github.com/digitalbazaar/forge",
    license: "BSD-3-Clause",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["certificate"],
    supportedProcessors: ["certificate-converter", "certificate-inspector"],
    supportedProviders: ["NodeForgeProvider"],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 450 * 1024,
    inputFormats: ["pem", "der", "crt", "cer", "p12", "pfx", "csr"],
    outputFormats: ["pem", "der", "p12", "pfx"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 5 * 1024 * 1024,
    description: "TLS/PKI implementation in pure JS — browser-side cert processing",
  },
  {
    id: "openssl",
    name: "OpenSSL (CLI)",
    package: "openssl (system)",
    homepage: "https://openssl.org",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["certificate"],
    supportedProcessors: ["certificate-converter"],
    supportedProviders: ["OpenSSLProvider"],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["pem", "der", "crt", "cer", "p12", "pfx", "p7b", "csr"],
    outputFormats: ["pem", "der", "p12", "pfx", "txt"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Battle-tested TLS library and CLI — all certificate format conversions",
  },

  // ── MISSING STUBS (referenced by Processor Registry — Phase 6B integration) ──

  {
    id: "native-js",
    name: "Native JavaScript",
    package: "(browser / Node built-in)",
    homepage: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    license: "W3C",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["code"],
    supportedProcessors: ["code-converter", "code-formatter", "code-minifier"],
    supportedProviders: [],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 0,
    inputFormats: ["json", "xml", "yaml", "toml", "csv", "tsv", "ini", "js", "ts", "css", "html", "sql"],
    outputFormats: ["json", "xml", "yaml", "toml", "csv", "tsv", "ini", "js", "css", "html"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 0,
    description: "Zero-dependency text and data manipulation using native JS APIs",
  },
  {
    id: "prettier",
    name: "Prettier",
    package: "prettier",
    homepage: "https://prettier.io",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["code"],
    supportedProcessors: ["code-formatter"],
    supportedProviders: [],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 5 * 1024 * 1024,
    inputFormats: ["js", "ts", "css", "html", "json", "md"],
    outputFormats: ["js", "ts", "css", "html", "json", "md"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "Opinionated code formatter — 40+ languages",
  },
  {
    id: "epub-js",
    name: "epub.js",
    package: "epubjs",
    homepage: "https://github.com/futurepress/epub.js",
    license: "FreeBSD",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["ebook"],
    supportedProcessors: ["ebook-converter", "ebook-viewer"],
    supportedProviders: [],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 1 * 1024 * 1024,
    inputFormats: ["epub"],
    outputFormats: ["html", "txt"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "EPUB renderer for browsers — renders ebooks to HTML",
  },
  {
    id: "calibre",
    name: "Calibre",
    package: "calibre (system)",
    homepage: "https://calibre-ebook.com",
    license: "GPL-3.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["ebook"],
    supportedProcessors: ["ebook-converter"],
    supportedProviders: [],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["epub", "mobi", "azw3", "fb2", "lit", "djvu", "cbz", "cbr", "txt", "html", "pdf"],
    outputFormats: ["epub", "mobi", "azw3", "pdf", "txt", "html", "fb2"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Comprehensive ebook management and conversion CLI",
  },
  {
    id: "subtitle-js",
    name: "subtitle.js",
    package: "subtitle",
    homepage: "https://github.com/gsantiago/subtitle.js",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["subtitle"],
    supportedProcessors: ["subtitle-converter", "subtitle-sync"],
    supportedProviders: [],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 30 * 1024,
    inputFormats: ["srt", "vtt", "ass", "ssa", "sub", "sbv"],
    outputFormats: ["srt", "vtt", "ass", "ssa", "sub", "sbv"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 5 * 1024 * 1024,
    description: "Parse and stringify subtitle formats (SRT, VTT, ASS, SSA)",
  },
  {
    id: "ass-js",
    name: "ASS.js",
    package: "assjs",
    homepage: "https://github.com/weizhenye/ASS",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["subtitle"],
    supportedProcessors: ["subtitle-converter"],
    supportedProviders: [],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 200 * 1024,
    inputFormats: ["ass", "ssa"],
    outputFormats: ["ass", "ssa", "srt"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 5 * 1024 * 1024,
    description: "Advanced SubStation Alpha subtitle renderer",
  },
  {
    id: "libraw",
    name: "LibRaw",
    package: "libraw (system)",
    homepage: "https://www.libraw.org",
    license: "LGPL-2.1",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["raw"],
    supportedProcessors: ["raw-converter", "raw-developer"],
    supportedProviders: [],
    tier: "server",
    priority: 1,
    status: "premium",
    inputFormats: ["cr2", "cr3", "nef", "arw", "dng", "raf", "rw2", "orf", "pef", "srw", "erf", "mrw", "x3f", "raw"],
    outputFormats: ["png", "jpg", "tiff"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "Library for reading and decoding RAW image files from 900+ cameras",
  },
  {
    id: "raw-engine",
    name: "RAW Engine (Abstraction)",
    package: "(abstraction over LibRaw / dcraw)",
    homepage: "https://www.libraw.org",
    license: "LGPL-2.1",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["raw"],
    supportedProcessors: ["raw-converter", "raw-developer"],
    supportedProviders: [],
    tier: "server",
    priority: 2,
    status: "future",
    inputFormats: ["cr2", "cr3", "nef", "arw", "dng", "raf", "rw2", "orf", "raw"],
    outputFormats: ["png", "jpg", "tiff", "webp"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "Phase 6B planned abstraction over LibRaw — unified RAW processing interface",
  },
  {
    id: "email-engine",
    name: "Email Engine (Abstraction)",
    package: "(abstraction — emailjs-mime-parser / mailparser)",
    homepage: "https://nodemailer.com",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["email"],
    supportedProcessors: ["email-converter", "email-extractor"],
    supportedProviders: [],
    tier: "hybrid",
    priority: 1,
    status: "primary",
    bundleSize: 400 * 1024,
    inputFormats: ["eml", "msg", "mbox", "emlx"],
    outputFormats: ["eml", "html", "txt", "pdf", "mbox"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 100 * 1024 * 1024,
    description: "Email parsing and conversion — browser-side MIME processing",
  },
  {
    id: "disk-image-engine",
    name: "Disk Image Engine (Abstraction)",
    package: "(server-side abstraction — planned)",
    homepage: "https://github.com/nicowillis/7zip-wasm",
    license: "MIT",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["disk-image"],
    supportedProcessors: ["disk-image-converter", "disk-image-extractor"],
    supportedProviders: [],
    tier: "server",
    priority: 1,
    status: "future",
    inputFormats: ["iso", "img", "bin", "vhd", "vmdk", "vdi", "qcow2", "dmg"],
    outputFormats: ["iso", "img", "vhd", "vmdk"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 0,
    description: "Phase 6B planned server-side disk image manipulation engine",
  },
  {
    id: "danfo-js",
    name: "Danfo.js",
    package: "danfojs",
    homepage: "https://danfo.jsdata.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["scientific"],
    supportedProcessors: ["scientific-converter", "scientific-visualizer"],
    supportedProviders: [],
    tier: "browser",
    priority: 1,
    status: "primary",
    bundleSize: 3 * 1024 * 1024,
    inputFormats: ["csv", "json"],
    outputFormats: ["csv", "json"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 200 * 1024 * 1024,
    description: "JavaScript data analysis library (Pandas-like) for scientific data",
  },
  {
    id: "hdf5-wasm",
    name: "h5wasm (HDF5 WASM)",
    package: "h5wasm",
    homepage: "https://github.com/usnistgov/h5wasm",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["scientific"],
    supportedProcessors: ["scientific-converter"],
    supportedProviders: [],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 4 * 1024 * 1024,
    inputFormats: ["hdf5", "h5"],
    outputFormats: ["csv", "json"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 500 * 1024 * 1024,
    description: "HDF5 file format reading in the browser via WebAssembly",
  },
  {
    id: "qpdf",
    name: "QPDF",
    package: "qpdf (system)",
    homepage: "https://qpdf.readthedocs.io",
    license: "Apache-2.0",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["pdf"],
    supportedProcessors: ["pdf-splitter", "pdf-protector", "pdf-unlocker"],
    supportedProviders: [],
    tier: "server",
    priority: 2,
    status: "secondary",
    inputFormats: ["pdf"],
    outputFormats: ["pdf"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 2 * 1024 * 1024 * 1024,
    description: "Content-preserving PDF manipulation — decryption, split, merge, linearize",
  },
  {
    id: "jscad",
    name: "@jscad",
    package: "@jscad/modeling",
    homepage: "https://openjscad.xyz",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["cad"],
    supportedProcessors: ["cad-converter"],
    supportedProviders: [],
    tier: "browser",
    priority: 2,
    status: "experimental",
    bundleSize: 2 * 1024 * 1024,
    inputFormats: ["jscad", "amf", "svg"],
    outputFormats: ["stl", "obj", "amf"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Constructive Solid Geometry (CSG) modelling in JavaScript",
  },
  {
    id: "proj4js",
    name: "Proj4js",
    package: "proj4",
    homepage: "https://proj4js.org",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["gis"],
    supportedProcessors: ["gis-converter", "gis-calculator"],
    supportedProviders: [],
    tier: "browser",
    priority: 3,
    status: "secondary",
    bundleSize: 300 * 1024,
    inputFormats: ["geojson", "wkt"],
    outputFormats: ["geojson", "wkt"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 50 * 1024 * 1024,
    description: "Coordinate systems transformations — reprojects GIS data between CRS",
  },
  {
    id: "remove-bg-api",
    name: "Remove.bg API",
    package: "remove.bg (cloud API)",
    homepage: "https://www.remove.bg/api",
    license: "Proprietary",
    browserSupport: false,
    serverRequired: true,
    supportedDomains: ["image"],
    supportedProcessors: ["image-background-remove"],
    supportedProviders: [],
    tier: "cloud",
    priority: 1,
    status: "premium",
    inputFormats: ["png", "jpg", "jpeg", "webp"],
    outputFormats: ["png"],
    supportsParallel: true,
    supportsStreaming: false,
    maxFileSizeBytes: 12 * 1024 * 1024,
    description: "AI-powered background removal cloud API",
  },
  {
    id: "turndown",
    name: "Turndown",
    package: "turndown",
    homepage: "https://github.com/mixmark-io/turndown",
    license: "MIT",
    browserSupport: true,
    serverRequired: false,
    supportedDomains: ["document"],
    supportedProcessors: ["document-converter", "document-to-text"],
    supportedProviders: [],
    tier: "browser",
    priority: 2,
    status: "secondary",
    bundleSize: 100 * 1024,
    inputFormats: ["html"],
    outputFormats: ["md"],
    supportsParallel: false,
    supportsStreaming: false,
    maxFileSizeBytes: 10 * 1024 * 1024,
    description: "HTML to Markdown converter — semantic, customisable rules",
  },
];

// ---------------------------------------------------------------------------
// REGISTRY CLASS
// ---------------------------------------------------------------------------

class LibraryRegistry {
  private byId: Map<string, LibraryDefinition>;
  private byDomain: Map<LibrarySupportedDomain, LibraryDefinition[]>;
  private byStatus: Map<LibraryStatus, LibraryDefinition[]>;

  constructor() {
    this.byId = new Map();
    this.byDomain = new Map();
    this.byStatus = new Map();

    for (const lib of LIBRARY_DEFINITIONS) {
      this.byId.set(lib.id, lib);

      for (const domain of lib.supportedDomains) {
        const existing = this.byDomain.get(domain) ?? [];
        existing.push(lib);
        this.byDomain.set(domain, existing);
      }

      const statusList = this.byStatus.get(lib.status) ?? [];
      statusList.push(lib);
      this.byStatus.set(lib.status, statusList);
    }
  }

  /** Get a library definition by ID */
  get(id: string): LibraryDefinition | undefined {
    return this.byId.get(id);
  }

  /** Get all libraries for a given domain, sorted by priority (lower = first) */
  forDomain(domain: LibrarySupportedDomain): LibraryDefinition[] {
    return [...(this.byDomain.get(domain) ?? [])].sort((a, b) => a.priority - b.priority);
  }

  /** Get browser-compatible libraries for a domain */
  browserLibrariesForDomain(domain: LibrarySupportedDomain): LibraryDefinition[] {
    return this.forDomain(domain).filter(l => l.browserSupport);
  }

  /** Get server-required libraries for a domain */
  serverLibrariesForDomain(domain: LibrarySupportedDomain): LibraryDefinition[] {
    return this.forDomain(domain).filter(l => l.serverRequired);
  }

  /** Get primary libraries only */
  primaryLibraries(): LibraryDefinition[] {
    return this.byStatus.get("primary") ?? [];
  }

  /** Get all libraries with a given status */
  withStatus(status: LibraryStatus): LibraryDefinition[] {
    return this.byStatus.get(status) ?? [];
  }

  /** Check if a library can convert between two formats */
  canConvert(libraryId: string, inputExt: string, outputExt: string): boolean {
    const lib = this.byId.get(libraryId);
    if (!lib) return false;
    return lib.inputFormats.includes(inputExt) && lib.outputFormats.includes(outputExt);
  }

  /** Get all library IDs that can handle a conversion */
  librariesForConversion(inputExt: string, outputExt: string): LibraryDefinition[] {
    return LIBRARY_DEFINITIONS.filter(l =>
      l.inputFormats.includes(inputExt) && l.outputFormats.includes(outputExt)
    ).sort((a, b) => a.priority - b.priority);
  }

  /** Total library count */
  get count(): number {
    return this.byId.size;
  }

  /** All library IDs */
  get ids(): string[] {
    return Array.from(this.byId.keys());
  }
}

export const libraryRegistry = new LibraryRegistry();
